apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc-config
  namespace: nextcloud
  labels:
    app: nextcloud
    type: config
spec:
  storageClassName: zimablade-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc-download
  namespace: nextcloud
  labels:
    app: nextcloud
    type: data
spec:
  storageClassName: zimablade-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nextcloud
  labels:
    app: postgres
    type: data
spec:
  storageClassName: zimablade-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---