version: '3'
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:29.0.0
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
    ports:
      - 1234:80
    restart: unless-stopped
networks:
  home:
    driver: bridge
